[tool.poetry]
name = "restmote"
version = "0.1.4"
description = ""
authors = ["argaen <manu.mirandad@gmail.com>","sdarwin <samuel.d.darwin@gmail.com>"]

[tool.poetry.dependencies]
requests = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
